config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/about'
  # get 'user/index', to 'user#index' (Same as bellow)
  get 'user/index'
  get 'event/index'
  get 'event/my'
  get 'session/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Automatically defining basic routes for user
  resources :user
  resources :org
  resources :event
  resources :account_activations, only: [:edit]

  # Its a vision to application root
  # get '/', to 'user#index' (Same as bellow)
  root 'static_pages#home'

  # Login routes
  get    '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'

end

app/models/event.rb
class Event < ApplicationRecord
    validates :nome, presence: true, length: { in: 3..100 }
    validates :local, presence: true
    validates :date, presence: true
    validates :time, presence: true

    has_many :hosts, dependent: :destroy
    has_many :users, through: :hosts

end

app/controllers/event_controller.rb
class EventController < ApplicationController

  def index
    @events = Event.all
  end

  def my
    unless logged_in?
      flash[:danger] = 'Você precisa estar logado para consultar seus eventos!'
      redirect_to "/session/new"
      return
    end
    @my_events = Event.joins(:users).where(users: {id: current_user.id})
  end

  def new
    unless logged_in?
      flash[:danger] = 'Você precisa estar logado para criar um evento!'
      redirect_to "/session/new"
      return
    end
  end

  def create

    unless logged_in?
      flash[:danger] = 'Você precisa estar logado para criar um evento!'
      redirect_to "/session/new"
      return
    end

    # Parameter that are obligatory to be passed and the ones that are optional
    flash[:success] = "Evento criado com sucesso!"
    @event = Event.new(event_params)

    unless @event.save
      @errors = @event.errors.full_messages
      render :new # views/new.html.haml
      return
    end

    host = Host.new(event: @event, user: current_user)
    host.save!

    redirect_to @event
  end

  def edit
    @event = Event.find(params[:id])
  end

  # Update the database
  def update

    @event = Event.find(params[:id])

    if @event.update_attributes(event_params)
      # Handle a successful update.
      redirect_to @event

    else
      render 'edit'
    end
  end


  # Showed when user is created
  def show
    if logged_in?
      @my_events = Event.joins(:users).where(users: {id: current_user.id})
    end

    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to event_index_path
  end

  private

    def event_params
        params
        .require(:event) # filters
        .permit(:nome,
                :info,
                :foto,
                :local,
                :date,
                :time,
                user_ids: [])
    end

end

app/helpers/event_helper.rb
module EventHelper
end

app/views/event/edit.html.haml
- if @errors
  = @errors

%html
  %head
    %title Editar Evento

%h1 Edição de Evento
.row
  .col-md-6.col-md-offset-3
    = form_with model: @event, local: true  do |f|
      = f.label :nome
      .marked *
      = f.text_field :nome, class: 'form-control'
      /%br
      /= f.label :foto
      /= f.url_field :foto, class: 'form-control'
      /= f.submit 'Submit', :foto => "form_submit"
      %br
      = f.label :info, "Descrição"
      .marked *
      = f.text_area :info, class: 'form-control'
      %br
      = f.label :local
      .marked *
      = f.text_field :local, class: 'form-control'
      %br
      = f.label :date, 'Data'
      .marked *
      = f.date_field :date, class: 'form-control'
      %br
      = f.label :time, 'Hora'
      .marked *
      = f.time_field :time, class: 'form-control'
      %br
      = f.submit "Salvar mudanças", class: "btn btn-primary"

app/views/event/index.html.haml
%head
  %title Eventos

%h1 Eventos

.col-md-10.col-md-offset-1
  %div.mylist
    %br
    .row
    %ul.events
      - @events.each do |ev|
        .column
        %li
          =link_to ev.nome, event_path(ev)
    %br
    %br
    .row
      .column
        = link_to "Evento+", new_event_path, class: "btn btn-primary"
    %br
    %br

app/views/event/my.html.haml
%head
  %title Meus Eventos

%h1 Meus Eventos

.col-md-10.col-md-offset-1
  %div.mylist
    %br
    .row
    %ul.events
      - @my_events.each do |mev|
        .column
        %li
          =link_to mev.nome, event_path(mev)
    %br
    %br
  .row
    .column
      = link_to "Evento+", new_event_path, class: "btn btn-primary"
  %br
  %br

app/views/event/new.html.haml
%head
  %title EVENTO+

- if @errors
  = @errors

%h1 EVENTO+
.row
  .col-md-6.col-md-offset-3
    = form_with scope: :event, url: '/event', local: true  do |f|

      = f.label :nome, 'Nome do Evento'
      .marked *
      = f.text_field :nome, class: 'form-control'
      /%br
      /= f.label :foto
      /= f.url_field :foto
      /= f.submit 'Submit', :foto => "form_submit"
      %br
      = f.label :info, 'Conte um pouco sobre o seu evento'
      .marked *
      = f.text_area :info, class: 'form-control'
      %br
      = f.label :local, 'Onde?'
      .marked *
      = f.text_field :local, class: 'form-control'
      %br
      = f.label :date, 'Que dia?'
      .marked *
      = f.date_field :date, class: 'form-control'
      %br
      = f.label :time, 'Que hora?'
      .marked *
      = f.time_field :time, class: 'form-control'
      %br
      = f.submit "Crie meu evento!", class: "btn btn-primary"

app/views/event/show.html.haml
%head
  %title= @event.nome
%br
%h1= @event.nome

.col-md-10.col-md-offset-1
  .describe
    %br
    %br
    = @event.info
    %br
    %br
    %br
    -#FOTO:
    -#%i= @event.foto
    -#br
    .row
      .column
        = image_tag("place.png", alt: "place")
        = @event.local
      .column
        = image_tag("schedule.png", alt: "day")
        = @event.date.strftime("%d/%m/%Y")
      .column
        = image_tag("clock.png", alt: "time")
        = @event.time.strftime("%R")
    %br
    %br
    %br


    - if logged_in? and @my_events.include? @event
      .row
        .column
          = link_to "Editar Evento", edit_event_path(@event.id), class: "btn btn-primary"
        .column
          = link_to "Deletar Evento", event_path(@event.id), method: :delete,
          data: {confirm: "Você tem certeza?"}, class: "btn btn-primary"
      %br
      %br
      %br
      %br