config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  get 'static_pages/about'
  # get 'user/index', to 'user#index' (Same as bellow)
  get 'user/index'
  get 'event/index'
  get 'event/my'
  get 'session/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Automatically defining basic routes for user
  resources :user
  resources :org
  resources :event
  resources :account_activations, only: [:edit]

  # Its a vision to application root
  # get '/', to 'user#index' (Same as bellow)
  root 'static_pages#home'

  # Login routes
  get    '/login',   to: 'session#new'
  post   '/login',   to: 'session#create'
  delete '/logout',  to: 'session#destroy'

end

app/views/layouts/application.html.haml
%html
  %head

    = favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type => "image/x-icon"
    %link{:href => "https://fonts.googleapis.com/css?family=Montserrat&display=swap", :rel => "stylesheet"}/

    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    %header.navbar.navbar-fixed-top.navbar-inverse
      .container
        = link_to image_tag("logo.png", alt: "logo"), root_path, id: "logo"
        %nav
          %ul.nav.navbar-nav.navbar-right

            - if logged_in?
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Lista de Eventos
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Todos os Eventos", event_index_path
                  %li= link_to "Meus Eventos", event_my_path
            - else
              %li= link_to "Eventos", event_index_path

            - if logged_in?
              %li= link_to "Evento+", new_event_path
            - else
              %li= link_to "User+", new_user_path

            - if logged_in?
              -#%li= link_to "Usuario", user_index_path
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  Minha conta
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Meu USP+", current_user
                  %li= link_to "Editar", edit_user_path(current_user)
                  %li.divider
                  %li
                    = link_to "Log Out", logout_path, method: :delete
            - else
              %li= link_to "Log In", session_new_path


    %body
    %br
    %br
    %br

    .container
      - flash.each do |message_type, message|
        %div{:class => "alert alert-#{message_type}"}= message

    = yield

    .container
      %br
      %footer.footer
        %small
          USPMais - A Universidade Fora da Sala de Aula
        %nav
          %ul
            %li= link_to "Sobre nós", static_pages_about_path
            %li= link_to "GitHub", 'http://github.com/mrfelipenoronha/uspmais'